[platformio]
src_dir = .

[env:nodemcuv2]
platform = espressif8266@2.6.3
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = spiffs
extra_scripts = pre:scripts/fix_pxmatrix_double_buffer.py

lib_deps =
  paulstoffregen/Time @ ^1.6.1
  gmag11/NtpClientLib @ 3.0.2-beta
  adafruit/Adafruit GFX Library
  https://github.com/2dom/PxMatrix.git#v1.6.0
